internproject/analytics/urls.py
from django.urls import path
from analytics.views import *

app_name = "analytics"

urlpatterns = [
    path('', base_page, name="fileadd"),
    path("add/", upload_file, name="fileupload"),
    path('select/', select_fields, name='select_field'),
    path('preprocess/', process_selectfield, name='preprocess'),
]

internproject/internproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('analytics.urls')),
]

internproject/analytics/models.py
from django.db import models

# Create your models here.

internproject/analytics/forms.py
from django import forms

choices = (
    (1, "2019-02-05_10:33:18"), (2, "2019-02-05_10:34:04")
)


class UploadFileForm(forms.Form):
    file = forms.FileField()


# class SelectdateForm(forms.Form):
#     date = forms.ChoiceField(choices=choices, widget=forms.Select(attrs={'onchange': 'actionform.submit();'}))

internproject/analytics/views.py
from .forms import *
from django.shortcuts import render
from django.shortcuts import *

options = (
    "2019-02-05_10:33:18", "2019-02-05_10:34:04"
)


def preprocess_file():
    with open("log.txt", "rb") as f:
        present = None
        data = {}
        while True:
            line = f.readline()
            if len(line) == 0:
                break
            string = str(line.strip())[2:-1]
            if string.find("query time is") != -1:
                first = ":".join(string.split(":")[1:])
                f.readline()
                second = str(f.readline().strip())[2:-1].split(":")[1]
                f.readline()
                third = str(f.readline().strip())[2:-1].split(":")[1]
                present = (first.strip(), second.strip(), third.strip())
                data[present] = []
            elif string.find("articles_title") != -1:
                temp = []
                temp.append("".join(str(string.strip()).split(":")[1:]).strip())
                temp.append("".join(str(f.readline().strip())[2:-1].split(":")[1:]).strip())
                temp.append("".join(str(f.readline().strip())[2:-1].split(":")[1:]).strip())
                temp.append("".join(str(f.readline().strip())[2:-1].split(":")[1:]).strip())
                data[present].append(temp)
    return data


def base_page(request):
    form = UploadFileForm()
    return render(request, "upload.html", {'form': form})


def handle_uploaded_file(f):
    with open('log.txt', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


def select_fields(request):
    data = preprocess_file()
    datetime = options[0]
    obj = None
    for i in data:
        if i[0] == datetime:
            obj = data[i]
        return render(request, 'select_form.html', {'object': obj, 'options': options, 'select_option': datetime})


def process_selectfield(request):
    data = preprocess_file()
    datetime = request.POST['date']
    obj = None
    for i in data:
        if i[0] == datetime:
            obj = data[i]
    return render(request, 'select_form.html', {'object': obj, 'options': options, 'select_option': datetime })


def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'])
            return redirect("analytics:select_field")
    else:
        form = UploadFileForm()
    return render(request, 'upload.html', {'form': form})

internproject/analytics/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js"
            integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U"
            crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js"
            integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9"
            crossorigin="anonymous"></script>


</head>
<body>
<main>
    <div class="page-content">
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
</main>
</body>
</html>

internproject/analytics/templates/detail_view.html
{% extends "_base.html"%}

{% block content %}

<center>
<h1>
    data processed
</h1>
<div>
    <table border="1px" style="width:80%">
        <tr>
            <th>articles_title</th>
            <th>articles_url</th>
            <th>distance</th>
            <th>enduserurl</th>
        </tr>
        {% for obj in object %}
            <tr>
                {% for small in obj %}
                <td style="text-align:center">{{small}}</td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
</div>
</center>

{% endblock %}

internproject/analytics/templates/select_form.html
{% extends "_base.html"%}

{% block content %}

{% load staticfiles %}
    <script src="{% static 'js/bootstrap.js' %}" ></script>

<center>
    <div style="margin-left:1000px;margin-top:50px">
        <form action="{% url 'analytics:preprocess' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <select name="date" onchange="this.form.submit()"
                    class="form-control" style="width:auto;" >
                {% for obj in options %}
                {% if obj == select_option %}
                <option selected>{{obj}}</option>
                {% else %}
                <option>{{obj}}</option>
                {% endif %}
                {% endfor %}
            </select>
        </form>
    </div>
    <div>
        <h1>
            data processed
        </h1>
        <table border="1px" style="width:80%">
            <tr>
                <th style="text-align:center">articles_title</th>
                <th style="text-align:center">articles_url</th>
                <th style="text-align:center">distance</th>
                <th style="text-align:center">enduserurl</th>
            </tr>
            {% for obj in object %}
            <tr>
                {% for small in obj %}
                <td style="text-align:center">{{small}}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </table>
    </div>
</center>
{% endblock %}

internproject/analytics/templates/upload.html
{% extends "_base.html"%}

{% block content %}

<center>
    <h1>
        Add file here
    </h1>
    <div>
        <div>
            <div style="height:200px">
                <div>
                    <br><br>
                    <form style="align:center" action="{% url 'analytics:fileupload' %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="file" name="file" onchange="this.form.submit()"/>
                        <br><br>
                        <!--<input class="btn btn-primary" type="submit"-->
                               <!--value="Submit">-->
                    </form>
                </div>
            </div>
        </div>
    </div>
</center>

{% endblock %}